app/config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from drf_yasg import openapi
from drf_yasg.views import get_schema_view

from members.views import signup_view
from posts.views import post_list

# drf-yasg 사용
schema_view = get_schema_view(
    openapi.Info(
        title='WPS Instagram API',
        default_version='v1',
        contact=openapi.Contact(email='qjaduddl94@gmail.com'),
    ),
    public=True,
)

urlpatterns_apis = [
    path('members/', include('members.urls.apis')),
    path('posts/', include('posts.urls.apis'))
]

urlpatterns = [
    path('doc/', schema_view.with_ui('redoc', cache_timeout=0)),
    path('apis/', include(urlpatterns_apis)),
    path('admin/', admin.site.urls),
    path('members/', include('members.urls.views')),
    path('posts/', include('posts.urls.views')),
    path('', signup_view, name='signup'),
    path('explore/tags/<str:tag>/', post_list, name='post-list-tag'),
]

urlpatterns += static(
    # URL 앞부분이 /media/이면
    prefix=settings.MEDIA_URL,
    # document_root 위치에서 나머지 path에 해당하는 파일을 리턴
    document_root=settings.MEDIA_ROOT,
)

app/members/urls.py
from django.urls import path

from members.views import login_view, signup_view, logout_view, naver_login


app_name = 'members'


urlpatterns = [
    path('login/', login_view, name='login'),
    path('logout/', logout_view, name='logout'),
    path('naver-login/', naver_login, name='naver-login'),

]

app/posts/urls.py
from django.urls import path

from posts.views import post_list, post_like, post_create, comment_create

app_name = 'posts'
urlpatterns = [
    path('', post_list, name='post_list'),
    path('<int:pk>/like', post_like, name='post-like'),
    path('create/', post_create, name='post-create'),
    path('<int:post_pk>/comments/create/', comment_create, name='comment-create'),

]

app/posts/models.py
import re

from django.db import models
from django.utils import timezone

from members.models import User


# Create your models here.


class Post(models.Model):
    """
    인스타그램의 포스트
    """
    TAG_PATTERNS = re.compile(r'#(\w+)')

    author = models.ForeignKey(User, on_delete=models.CASCADE)
    content = models.TextField(blank=True)
    content_html = models.TextField(blank=True)
    like_users = models.ManyToManyField(User, through='PostLike', related_name='like_post_set')
    tags = models.ManyToManyField('Tag', verbose_name='해시태그 목록', related_name='posts', blank=True)
    created = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return self.author.username

    def _save_html(self):
        self.content_html = re.sub(self.TAG_PATTERNS, r'<a href="/explore/tags/\g<1>">#\g<1></a>', self.content)

    def _save_tags(self):
        tag_name_list = list(set(re.findall(self.TAG_PATTERNS, self.content)))
        tags = []
        for tag in tag_name_list:
            tags.append(Tag.objects.get_or_create(name=tag)[0])
        self.tags.set(tags)

    def save(self, *args, **kwargs):
        self._save_html()
        super().save(*args, **kwargs)
        self._save_tags()


class PostImage(models.Model):
    """
    각 포스트의 사진
    """
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    image = models.ImageField(upload_to='posts/images')


class PostComment(models.Model):
    """
    각 포스트의 댓글(m2m)
    """
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    content = models.TextField()


class PostLike(models.Model):
    """
    사용자가 좋아요 누른 Post정보를 저장
    Many-To-Many 필드를 중간모델(Intermediate Model)을 거쳐 사용
    언제 생성되었는지를 Extra field로 저장 (create)
    """
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    created_date = models.DateTimeField(auto_now_add=True)


class Tag(models.Model):
    """
    HashTag의 Tag를 담당
    Post 입장에서 post.add()로 연결된 전페 Tag를 불러 올 수 있어야 함
    Tag입장에서 tah.posts.all()로 연결된 전페 Post를 불러올 수 있어야 함

    Django admin에서 결과를 볼 수 있도록 admin.py에 적절히 내용 기록

    중개모델(Intermediate model()을 사용할 필요 없음
    """

    name = models.CharField("태그명", max_length=100)

    # posts = models.ManyToManyField(Post)

    def __str__(self):
        return self.name

app/posts/forms.py
from django import forms


class PostCreateForm(forms.Form):
    """
    이 Form에 들어갈 입력요소
        Image
        text
    """

    image = forms.ImageField(
        widget=forms.ClearableFileInput(
            attrs={
                'multiple': True,
            }
        )
    )

    content = forms.CharField(max_length=200, widget=forms.Textarea())


class CommentCreateForm(forms.Form):
    content = forms.CharField(
        max_length=20,
        widget=forms.Textarea(

        )
    )

    def save(self, post, author):
        return post.postcomment_set.create(
            author=author,
            content=self.cleaned_data['content'],
        )

app/posts/urls/views.py
from django.urls import path

from ..views import post_list, post_like, post_create, comment_create, comment_list

app_name = 'posts'
urlpatterns = [
    path('', post_list, name='post_list'),
    path('<int:pk>/like', post_like, name='post-like'),
    path('create/', post_create, name='post-create'),
    path('<int:post_pk>/comments/create/', comment_create, name='comment-create'),
    path('<int:post_pk>/comments/', comment_list, name='comment_list'),

]

app/posts/views.py
from django.http import HttpResponse
from django.shortcuts import render, redirect

# Create your views here.
from posts.forms import PostCreateForm, CommentCreateForm
from posts.models import Post, PostLike, PostComment


def post_list(request, tag=None):
    # 1. 로그인 완료 후 이 페이지로 이동하도록 함
    # 2. index에 접근할 때 로그인이 되어 있다면, 이 페이지로 이동하도록 함
    #    로그인이 되어있는지 확인:
    #       request.user.is_authenticated가 True인지 체크
    #
    # URL:      /posts/  (posts.urls를 사용, config.urls에서 include)
    #           app_name: 'posts'
    #           url name: 'post-list'
    #           -> posts:post-list
    # Template: templates/posts/post-list.html
    #           <h1>Post List</h1>

    # 'posts'라는 키로 모든 Post QuerySet을 전달
    #  (순서는 pk의 역순)
    # 그리고 전달받은 QuerySet을 순회하며 적절히 Post내용을 출력
    if tag is not None:
        posts = Post.objects.filter(tags__name__iexact=tag).order_by('-pk')
    else:
        posts = Post.objects.order_by('-pk')
    comment_form = CommentCreateForm()
    context = {
        'posts': posts,
        'comment_form': comment_form,
    }
    return render(request, 'posts/post-list.html', context)


#
# def post_list_by_tag(request, tag):
#     """
#     URL:        /explore/tags/<tag문자열>/
#     template:   /posts/post-list.html
#
#     <tag문자열>인 Tag를 자신(post).tags에 가지고 있는 경우의 Post 목록만 돌려줘야 함
#     이 내용 외에는 위의 post_list와 내용 동일
#
#     """
#     # URL: /explore/tags/<tag문자열>/
#     posts = Post.objects.filter(tags__name__iexact=tag).order_by('-pk')
#     comment_form = CommentCreateForm()
#     context = {
#         'posts': posts,
#         'comment_form': comment_form,
#     }
#     return render(request, 'posts/post-list.html', context)


def post_like(request, pk):
    """
    pk가 pk인 Post에 대한
    1. Postlike를 생성한다
    2. 만약 해당 객체가 이미 있다면, 삭제한다.
    3. posts:post_list로 redirect한다.
    :param request:
    :param pk:
    :return:
    """

    post = Post.objects.get(pk=pk)

    post_like_qs = PostLike.objects.filter(post=post, user=request.user)

    if post_like_qs.exists():
        post_like_qs.delete()

    else:
        PostLike.objects.create(post=post, user=request.user)

    return redirect('posts:post_list')

    # try:
    #     like1 = PostLike.objects.get(post=post, user=request.user)
    #     like1.delete()
    #
    #
    # except PostLike.DoesNotExist:
    #     like1 = PostLike.objects.create(post=post, user=request.user)
    #
    # return redirect('posts:post_list')


def post_create(request):
    """
    url:        /posts/create name='post-create'
    Template:   /posts/posts-create.html

    forms.PostCreateForm을 생성한다.

    :param request:
    :return:
    """

    if request.method == 'POST':
        images = request.FILES.getlist('image')
        content = request.POST['content']

        post = Post.objects.create(author=request.user, content=content)
        for image in images:
            print(image, type(image))
            post.postimage_set.create(image=image)

        return redirect('posts:post_list')
        pass
    else:
        form = PostCreateForm()
        context = {
            'form': form
        }
        return render(request, 'posts/post-create.html', context)


def comment_create(request, post_pk):
    # URL: /posts/<int:post_pk>/comments/create/
    # Template: 없음 (post-list.html내에 Form을 구현)
    #  post-list.html 내부에서, 각 Post마다 자신에게 연결된 PostComment목록을 보여주도록 함
    #   보여주는형식은
    #    <ul>
    #     <li><b>작성자명</b> <span>내용</span></li>
    #     <li><b>작성자명</b> <span>내용</span></li>
    #    </ul>
    if request.method == 'POST':
        post = Post.objects.get(pk=post_pk)
        # Form인스턴스를 만드는데, data에 request.POST로 전달된 dict를 입력
        form = CommentCreateForm(data=request.POST)
        # Form인스턴스 생성시, 주어진 데이터가
        # 해당 Form이 가진 Field들에 적절한 데이터인지 검증
        if form.is_valid():
            form.save(post=post, author=request.user)
        return redirect('posts:post_list')


def comment_list(request, post_pk):
    comments = PostComment.objects.filter(post=post_pk)
    return render(request, 'comment_list.html', context={'comments': comments})

app/templates/posts/post-create.html
{% extends 'base.html' %}



{% block content %}
    <form action="" method="post" , enctype="multipart/form-data">
        {% csrf_token %}
        {% for field in form %}
            <div class="form-group">
                {{ field }}
            </div>
        {% endfor %}
        <button type="submit" class="btn btn-primary">작성</button>
    </form>
{% endblock %}

app/templates/posts/post-list.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
    <div class="text-center">User: {{ request.user }}</div>
    <div class="text-center">Authenticate : {{ request.user.is_authenticated }}</div>

    <div>
        <a href="{% url 'members:logout' %}">logout</a>
    </div>
    <div>
        <a href="{% url 'posts:post-create' %}">포스트 추가</a>
    </div>
    <div class="container-fluid">
        {% for post in posts %}

            <div class="card col-10  ml-auto mr-auto">
                <div>{{ post.content_html | safe}}</div>
                <p class="text-right">{{ post.created }}</p>
                {% for postimage in post.postimage_set.all %}
                    <div>
                        <!--
                            이 포스트가 가진 모든 PostImage를 추력
                            <img src="무언가.image.url">
                        -->
                        <img src="{{ postimage.image.url }}" alt="">
{#                        <p>{{ postimage.image.url }}</p>#}
                    </div>
                {% endfor %}
                <form action="{% url 'posts:post-like' pk=post.id %}" class="form-group" method="post">
                    {% csrf_token %}

                    {#                {% if user in post.like_users.all %}#}
                    {% if post in user.like_post_set.all %}
                        <button type="submit" class="btn btn-primary float-right">like 취소</button>
                    {% else %}
                        <button type="submit" class="btn btn-outline-primary float-right">like</button>
                    {% endif %}


                </form>
                <div>
                    <ul>
                        {% for comment in post.postcomment_set.all %}
                            <li>
                                <b>{{ comment.author.username }}</b>
                                <span>{{ comment.content }}</span>
                            </li>
                        {% endfor %}
                    </ul>
                    <div>
                        <!-- Comment를 작성하는 Form -->
                        <form action="{% url 'posts:comment-create' post_pk=post.pk %}" method="POST">
                            {% csrf_token %}
                            {{ comment_form }}
                            <button type="submit">작성</button>
                        </form>
                    </div>
                </div>
            </div>


        {% endfor %}

    </div>


    {#    <h1>post list!!!</h1>#}
    {#    <ul>#}
    {#        {% for post in posts %}#}
    {#            <li>#}
    {#                <div>#}
    {#                    <p>{{ post.content }}</p>#}
    {#                    <p>{{ post.created }}</p>#}
    {#                </div>#}
    {#            </li>#}
    {##}
    {#        {% endfor %}#}
    {##}
    {#    </ul>#}
{% endblock %}