app/config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from drf_yasg import openapi
from drf_yasg.views import get_schema_view

from members.views import signup_view
from posts.views import post_list

# drf-yasg 사용
schema_view = get_schema_view(
    openapi.Info(
        title='WPS Instagram API',
        default_version='v1',
        contact=openapi.Contact(email='qjaduddl94@gmail.com'),
    ),
    public=True,
)

urlpatterns_apis = [
    path('members/', include('members.urls.apis')),
    path('posts/', include('posts.urls.apis'))
]

urlpatterns = [
    path('doc/', schema_view.with_ui('redoc', cache_timeout=0)),
    path('apis/', include(urlpatterns_apis)),
    path('admin/', admin.site.urls),
    path('members/', include('members.urls.views')),
    path('posts/', include('posts.urls.views')),
    path('', signup_view, name='signup'),
    path('explore/tags/<str:tag>/', post_list, name='post-list-tag'),
]

urlpatterns += static(
    # URL 앞부분이 /media/이면
    prefix=settings.MEDIA_URL,
    # document_root 위치에서 나머지 path에 해당하는 파일을 리턴
    document_root=settings.MEDIA_ROOT,
)

app/members/urls.py
from django.urls import path

from members.views import login_view, signup_view, logout_view, naver_login


app_name = 'members'


urlpatterns = [
    path('login/', login_view, name='login'),
    path('logout/', logout_view, name='logout'),
    path('naver-login/', naver_login, name='naver-login'),

]

app/posts/urls.py
from django.urls import path

from posts.views import post_list, post_like, post_create, comment_create

app_name = 'posts'
urlpatterns = [
    path('', post_list, name='post_list'),
    path('<int:pk>/like', post_like, name='post-like'),
    path('create/', post_create, name='post-create'),
    path('<int:post_pk>/comments/create/', comment_create, name='comment-create'),

]

app/templates/base.html
{% load static %}

<!doctype html>
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="{% static 'bootstrap/bootstrap.css' %}">
    <title>Instagram</title>
    {% block head %}{% endblock %}
</head>
<body>
<div id="wrap">
    {% block content %}
    {% endblock %}
</div>
</body>
</html>

app/templates/comment_list.html
{% for comment in comments %}
    <p>{{ comment.author }}</p>
    <p>{{ comment.content }}</p>
{% endfor %}

app/templates/index.html
{#{% extends 'base.html' %}#}
{#{% load static %}#}
{##}
{#{% block head %}#}
{#<link rel="stylesheet" href="{% static 'css/index.css' %}">#}
{#{% endblock %}#}
{##}
{#{% block content %}#}
{##}
    {#<h1>index!</h1>#}
    {#<div>{{ request.user }}</div>#}
    {#<div>{{ request.user.is_authenticated }}</div>#}
    {#<div>{{ request}}</div>#}
{#    <div class="container-fluid">#}
{#        <div class="mr-auto ml-auto mt-3#}
{#                    col-lg-4#}
{#                    col-md-6#}
{#                    col-sm-8#}
{#                    col-10">#}
{#            <div class="top-box card text-center p-4">#}
{#                {{ request.user }}#}
{#                {{ request.user.is_authenticated }}#}
{#                <h1>Instagram</h1>#}
{#                <p class="text-secondary">친구들의 사진과 동영상을 보려면 가입하세요</p>#}
{##}
{#                <button type="button" class="btn btn-primary btn-block">Facebook으로 로그인</button>#}
{#                <hr>#}
{#                <form action="{% url 'members:signup' %}" method="post">#}
{#                    {% csrf_token %}#}
{#                    <div class="form-group">#}
{#                        <input type="text" class="form-control" placeholder="휴대폰 번호 또는 이메일 주소" name="email">#}
{#                    </div>#}
{#                    <div class="form-group">#}
{#                        <input type="text" class="form-control" placeholder="성명" name="username">#}
{#                    </div>#}
{#                    <div class="form-group">#}
{#                        <input type="text" class="form-control" placeholder="사용자 이름" name="name">#}
{#                    </div>#}
{#                    <div class="form-group">#}
{#                        <input type="password" class="form-control" placeholder="비밀번호" name="password">#}
{#                    </div>#}
{##}
{#                    <button type="submit" class="btn btn-primary btn-block mb-3">가입</button>#}
{##}
{##}
{#                </form>#}
{#                <p class="text-secondary">가입하면 instagram의 약관 데이터 정책 및 쿠키 정책에 동의하게 됩니다</p>#}
{#            </div>#}
{##}
{#            <div class="card text-center p-4 mt-3 mb-3">#}
{#                <span>계정이 있으신가요?</span>#}
{#                <a href="{% url 'members:login' %}">로그인</a>#}
{##}
{##}
{#            </div>#}
{##}
{#        </div>#}
{#    </div>#}
{#{% endblock %}#}